# Практическое занятие по линейной алгебре

В этом разделе вы примените изученные концепции линейной алгебры, используя Python и библиотеку NumPy. Убедитесь, что у вас установлен NumPy:



In [1]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.



## 1. **Операции с векторами и матрицами**

### 1.1 Создание векторов и матриц



In [2]:
import numpy as np

# Создание вектора
vector = np.array([1, 2, 3])

# Создание матрицы
matrix = np.array([[1, 2], [3, 4], [5, 6]])

print("Вектор:", vector)
print("Матрица:n", matrix)

Вектор: [1 2 3]
Матрица:n [[1 2]
 [3 4]
 [5 6]]



### 1.2 Сложение векторов и матриц



In [3]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Сложение векторов
vector_sum = vector_a + vector_b

matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Сложение матриц
matrix_sum = matrix_a + matrix_b

print("Сумма векторов:", vector_sum)
print("Сумма матриц:n", matrix_sum)

Сумма векторов: [5 7 9]
Сумма матриц:n [[ 6  8]
 [10 12]]



### 1.3 Скалярное произведение двух векторов

Скалярное произведение определяется как:



$$
\mathbf{a} \cdot \mathbf{b} = \sum_{i=1}^{n} a_i b_i
$$
Вы можете вычислить его в Python следующим образом:



In [4]:
# Скалярное произведение двух векторов
dot_product = np.dot(vector_a, vector_b)
print("Скалярное произведение:", dot_product)

Скалярное произведение: 32



## 2. **Умножение матриц**

Умножение матриц следует определенным правилам. Давайте выполним его с помощью NumPy:



In [5]:
# Умножение матриц
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

matrix_product = np.dot(matrix_a, matrix_b)
print("Произведение матриц:n", matrix_product)

Произведение матриц:n [[19 22]
 [43 50]]



Формула для умножения матриц:



$$
(A \cdot B)_{ij} = \sum_{k} A_{ik} B_{kj}
$$
## 3. **Единичная матрица и обращение матрицы**

### 3.1 Единичная матрица

Единичная матрица — это квадратная матрица, в которой все диагональные элементы равны 1, а остальные элементы равны 0:



In [6]:
identity_matrix = np.eye(3)
print("Единичная матрица:n", identity_matrix)

Единичная матрица:n [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



### 3.2 Обратная матрица

Обратная матрица $A$ — это матрица $A^{-1}$, такая что:



$$
A \cdot A^{-1} = I
$$
Где $I$ — единичная матрица.

Вы можете вычислить обратную матрицу с помощью NumPy:



In [7]:
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print("Обратная матрица:n", inverse_matrix)

Обратная матрица:n [[-2.   1. ]
 [ 1.5 -0.5]]



## 4. **Собственные значения и собственные векторы**

Собственные значения и собственные векторы можно вычислить с помощью функции `np.linalg.eig()`. Давайте вычислим их для матрицы 2x2:



In [8]:
matrix = np.array([[4, -2], [1, 1]])

# Вычисление собственных значений и собственных векторов
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Собственные значения:", eigenvalues)
print("Собственные векторы:n", eigenvectors)

Собственные значения: [3. 2.]
Собственные векторы:n [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]



Уравнение для собственных значений:



$$
A \mathbf{v} = \lambda \mathbf{v}
$$
Где $A$ — матрица, $\lambda$ представляет собственные значения, а $\mathbf{v}$ представляет собственные векторы.

## 5. **Практические упражнения**

### Упражнение 1: Операции с матрицами

1. Создайте две матрицы 3x3 и выполните поэлементное сложение и умножение матриц.
2. Вычислите скалярное произведение двух 3-мерных векторов.

### Упражнение 2: Обратная и единичная матрицы

1. Сгенерируйте единичную матрицу 4x4.
2. Создайте матрицу 2x2, найдите её обратную матрицу и проверьте, что умножение матрицы на её обратную возвращает единичную матрицу.

### Упражнение 3: Собственные значения и собственные векторы

1. Создайте матрицу 3x3 и вычислите её собственные значения и собственные векторы.
2. Проверьте уравнение для собственных значений: $A \mathbf{v} = \lambda \mathbf{v}$ для наибольшего собственного значения.


In [10]:
matrix_a=np.array([[3,5,7],[1,3,5],[2,4,6]])
matrix_b=np.array([[1,2,3],[4,5,6],[7,8,9]])

#Сложение матриц
matrix_sum=matrix_a+matrix_b
print(matrix_sum)

#Умножение матриц
matrix_product=np.dot(matrix_a,matrix_b)
print(matrix_product)


[[ 4  7 10]
 [ 5  8 11]
 [ 9 12 15]]
[[ 72  87 102]
 [ 48  57  66]
 [ 60  72  84]]


In [11]:
vector_a=np.array([10,15,20])
vector_b=np.array([3,5,7])

#Скалярное произведение
dot_product=np.dot(vector_a,vector_b)
print(dot_product)  

245


In [12]:
identity_matrix = np.eye(4)
print("Единичная матрица:n", identity_matrix)


Единичная матрица:n [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
matrix=np.array([[7,9],[3,5]])
inverse_matrix=np.linalg.inv(matrix)
print("Обратная матрица:\n", inverse_matrix)

# Умножим марицу на ee обратную
matrix_product=np.dot(matrix,inverse_matrix)
matrix_product_rounded=np.round(matrix_product,6)
print("Произведение матрицы и обратной:\n", matrix_product_rounded)





Обратная матрица:
 [[ 0.625 -1.125]
 [-0.375  0.875]]
Произведение матрицы и обратной:
 [[ 1.  0.]
 [-0.  1.]]


In [29]:
matrix=np.array([[1,9,10],[4,3,5],[7,8,2]])
eigenvalues,eigenvectors=np.linalg.eig(matrix)
print("Собственные значения:\n", eigenvalues)
print("Собственные векторы:\n", eigenvectors)

# Находим наибольший собственный вектор и наибольшее собственное значение
max_eigenvalue_index=np.argmax(eigenvalues)
max_eigenvalue = eigenvalues[max_eigenvalue_index]
print("Наибольшеемсобственное значение:\n",max_eigenvalue)
max_eigvec = eigenvectors[:, max_eigenvalue_index]
print("Максимальный собственный вектор:\n", max_eigvec)

# Проверим уравнение A*v=lambda*v
lhs=lhs = np.dot(matrix, max_eigvec)  # Левая часть уравнения A*v
rhs = max_eigenvalue_index * max_eigvec  # Правая часть уравнения lambda*v





Собственные значения:
 [15.81301138 -6.88148353 -2.93152785]
Собственные векторы:
 [[-0.67066876 -0.78914638  0.5127263 ]
 [-0.44186345  0.00868969 -0.7285966 ]
 [-0.59578529  0.6141437   0.45415717]]
Наибольшеемсобственное значение:
 15.813011380425081
Максимальный собственный вектор:
 [-0.67066876 -0.44186345 -0.59578529]
